### ISSUE TITLE
Compatibility Issue: Library Chat Commands

### ISSUE THREAD

**Issue by shinkei13** [orcnog/autocomplete-whisper#38]
It appears that this module and [Library Chat Commands](https://github.com/League-of-Foundry-Developers/Chat-Commands-Lib) both utilize the same method to register "keydown.menufocus". It appears that because of that, you cannot use both modules without breaking the keyboard functionality of Autocomplete Whisper.

Chat Commands Autocomplete still retains keyboard functionality however.

**Comment by orcnog** [comment]
I've spoken with @cswendrowski about a possible change to core that could solve this for everyone, provided we all follow up by altering our own code to leverage that change.

You can view the issue I created here: https://gitlab.com/foundrynet/foundryvtt/-/issues/5300

If this gets implemented, I'll fix autocomplete whisper so that it's not breaking any other modules competing for this same keybind... Chat-Commands-Lib and DSA5 need to do their part as well.

**Comment by orcnog** [comment]
Solution implemented.  See comment here: https://github.com/orcnog/autocomplete-whisper/issues/37#issuecomment-1254019421
